### ISSUE TITLE
Are you doing projective transformations?

### ISSUE THREAD

**Issue by eonist** [JustinFincher/JZtvOSParallaxButton#1]
Like

https://en.wikipedia.org/wiki/Homography

**Comment by JustinFincher** [comment]
Hi,
sorry for my poor English, I have some difficulty reading the wikipedia and understand what "Homography" is.... I will try to explain what I did to achieve this effect.
CALayer transformation by default can only do orthographic projection, and I am using a code snippet from [this](http://stackoverflow.com/questions/347721/how-do-i-apply-a-perspective-transform-to-a-uiview) to make projective transform, and with an orthographic camera from the front it looks like this : 
![](http://anius.io/img/2015/11/tvOS/tvOSButtonGif_2.gif)

**Comment by eonist** [comment]
Would it be possible to apply it to a cgPath?

**Comment by JustinFincher** [comment]
I haven't tried yet, maybe try with `CGPathCreateCopyByTransformingPath` by giving a `CGAffineTransform`, but I am not sure that CGAffineTransform can be converted from CATransform3D with no capabilities lost....

**Comment by eonist** [comment]
The native method named CATransform3DGetAffineTransform could work. If not directly on a cgPath transorm then possibly
 by manually translating each point in the path. There is little information available on this subject. Could be interesting to look into. Here is one o found: http://stackoverflow.com/questions/11138310/using-a-cgpoint-and-catransform3d-to-find-a-new-point-on-a-line

And something ongithub: https://github.com/agens-no/AGGeometryKit

**Comment by JustinFincher** [comment]
WOW, that's cool, thanks !
And if you want to deform UIView, I think you can use https://github.com/Ciechan/BCMeshTransformView ;-)

**Comment by eonist** [comment]
Im going to do some projective transforming math and maybe mesh transforming too. In a month or two. But with cgPath's. Thanks for your replies. Have agood day.
